[package]
name = "frappslib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.12"

[dev-dependencies]
mockito = "0.31.0"
tokio-test = "0.4.2"
wiremock = "0.5.15"
