[package]
name = "frapps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frappslib = {path = "../frappslib"}
tokio = { version = "1.21.2", features = ["full"] }
